.travis.yml, build/roslib.js, src/RosLib.js, src/actionlib/index.js, src/core/index.js, src/math/index.js, src/mixin.js, src/tf/index.js, src/urdf/index.js
This allows users to do
```js
> var Ros = require("roslib/src/core")
{ Ros: [Function: Ros],
Topic: [Function: Topic],
Message: [Function: Message],
Param: [Function: Param],
Service: [Function: Service],
ServiceRequest: [Function: ServiceRequest],
ServiceResponse: [Function: ServiceResponse]
}
```
Fixes #157
=> Index components of roslib

src/core/Topic.js
As mentionned in issue #163, Rosbridge_suite expects queue_length parameter on subscription to handle queues. Queue_size was not passed until now. This fixes it.
=> Added queue_length parameter to topic subscription message

src/core/Ros.js
Update for finding a list of service or topic as specific type.
It is related following pull-request.
https://github.com/RobotWebTools/rosbridge_suite/pull/172
=> Add function that find service and topic as specific type

src/urdf/UrdfLink.js, src/urdf/UrdfMaterial.js, src/urdf/UrdfModel.js, test/urdf.test.js
These commits will add missing Urdf features. Note that this will break api compatibility, since the UrdfLink.visual param is missing. I am adding a PR to ros3djs as well.
=> Add Urdf features: multiple visuals and material linking

src/core/Topic.js, src/math/Quaternion.js
This merge request adds a Quaternion function and fixes a misconception in a previous patch of Topic.js
According to the roslib websocket protocol queue_size and queue_length are different things and should not come from the same (default) parameter.
=> Indigo devel

package.json, src/urdf/UrdfModel.js, src/util/DOMParser.js, src/util/shim/DOMParser.js, test/require-shim.js, test/urdf.test.js
The current DOMParser shim is not used, you can verify this by fixing the `package.json`:
```
"../util/DOMParser": "./src/util/shim/DOMParser.js"
```
The `xmlshim` package provides its own shim (which is already used in the roslibjs build). This pull request makes it more clear which shim is used.
=> remove the (unused) DOMParser shim

.jshintrc, package.json, src/core/SocketAdapter.js
roslibjs component of https://github.com/RobotWebTools/rosbridge_suite/issues/169
Pairs with https://github.com/RobotWebTools/rosbridge_suite/pull/190
Current problem: BSON is a huge dependency. 
```
-rw-rw-r-- 1 dlu dlu  65K Jul 10 17:08 roslib.js
-rw-rw-r-- 1 dlu dlu  27K Jul 10 17:09 roslib.min.js
```
```
-rw-rw-r-- 1 dlu dlu 275K Jul 10 17:09 roslib.js
-rw-rw-r-- 1 dlu dlu 104K Jul 10 17:09 roslib.min.js
```
Is that a problem? Is there a better way?
=> BSON Decoding of Binary Objects

package.json, src/urdf/UrdfModel.js, src/util/shim/xmldom.js, test/require-shim.js, test/urdf.test.js
xmldom is a full JavaScript implementation of DOMParser with the same functionality. It is a lot more used and so I think it is more reliable (217.411 downloads in the last week vs 88).
As a result this project will no longer depend on libxmljs which makes it easier to install on platforms such as windows. All tests on both node and browser still run.
As a side effect I had to reintroduce `shim/xmldom.js` to keep the build size small. I also replaced the xpath `evaluate` call with `documentElement` because we no longer have that. Could that become a problem?
=> replace xmlshim with xmldom

package.json
=> canvas version bump to use for both node version 0.10.x and 0.12.x

src/tf/TFClient.js
If the tf2_web_republisher was not running in the global namespace or with a different name the TFClient wasn't able to connect to it. With this change you can specify the action server name of the tf2_web_republisher.
=> Added serverName option to TFClient

src/actionlib/ActionClient.js, src/tf/TFClient.js
Omitting certain channels of the action client will make the action protocol incomplete. However, this can reduce the network load of the websocket and the action protocol will still work in certain use cases.
=> Add options to omit the feedback, status or result channel of ActionClient.

test/examples/setup_examples.launch, test/examples/setup_examples.sh
- use roslaunch to deduplicate launching effort
- use rostopic info to check for the last node's topic existance
- return a status code based on if it succeeded
=> Make the travis script more robust

src/core/Service.js, src/core/SocketAdapter.js
Updates roslib so that it can advertise services in addition to calling them.
Example Usage
```
let addTwoInts = new roslib.Service({
ros: rosConn,
name: '/add_two_ints',
serviceType: 'beginner_tutorials/AddTwoInts'
});
addTwoInts.advertise((req, resp) => {
resp.sum = req.a + req.b
return true;
});
```
=> Update roslibjs to advertise Services

src/tf/TFClient.js
This parameter is needed if your tf2_web_republisher is running in a namesspace.
=> Added repubServiceName parameter to TFClient.

src/actionlib/ActionListener.js, src/actionlib/index.js
I had the need to listen for arbitrary goal related messages, not just for goals created in my JS client. I wish to monitor goals and display feedback and status for goals created by another client.
As such I built this action listener (based on the existing action client) that let me subscribe to the topics directly rather than filtering based on the goals that I'd created.
I wasn't sure if there is apetite for this feature, so thought I'd submit the pull request to seek interest.
=> An action listener for all actions not just for goals created by client

.npmignore
The package is documented (https://www.npmjs.com/package/roslib) as including roslib.js and roslib.min.js from
the build directory, but they're currently excluded. This will also make
it easier for people who want to use roslib.js without using RequireJS
or another loader.
=> Include build directory in NPM package

README.md
The demo link now points to the demos page, instead of the homepage.
=> Change demo link

package.json, src/util/shim/EventEmitter2.js
I upgraded the EventEmitter2 version in package.json and removed the shim. This allows roslibjs to be used in webpack projects.
=> Upgraded EventEmitter2 and removed shim

package.json
License name updated to match the LICENSE file. This is in reference to this change in NPM https://github.com/npm/npm/issues/8918
=> Updating the licence so SPDX stops complaining

.travis.yml, Dockerfile, package.json, test/build.bash, test/build.sh, test/examples/check-topics.example.js, test/examples/karma.conf.js, test/examples/params.examples.js, test/examples/setup_examples.sh
* Use docker. Thanks to @minggangw for a nice example
* Test against kinetic version rosbridge and node version 4.2.6
TODO: 
* re-enable delete param test after merging [rosbridge_suite#284](https://github.com/RobotWebTools/rosbridge_suite/pull/284)
* Configure travis to use docker cache
=> Update travis configuration

examples/simple.html, src/core/Service.js
The documentation for ```Service.advertise()``` was wrong, and there was no example to show users how to advertise a service.
As a side note, maybe a ```rospy```-style Service handler (return the response object, return ```None```/```undefined``` to signal a failure) would be more intuitive? If the callback accidentially overwrites the provided ```response``` object (see my comment in Service.js:74), that could lead to very unintuitive bugs.
=> add example for advertise_service and fix documentation

src/core/Service.js
We want to reuse the roslibjs as the front-end JavaScript library by
leveraging the ros2-web-bridge in ROS2. But the current roslibjs doesn't
transmit the service type when calling a service, which is a necessary
element when sending the request in ROS2.
This patch adds this information to make it compatible with ROS2.
=> Add the type of service when executing 'call_service'

Gruntfile.js, src/util/shim/.jshintrc, src/util/shim/WebSocket.js, src/util/shim/decompressPng.js, src/util/shim/xmldom.js
The files in /shim is only used in browsers (remapped in the browser
field of package.json) when using build tools. Browsers do not have the
global propery which is a node thing. Browsers instead have the global
namespace window.
This commit solve my problem of importing roslib in my application and
building with webpack 4 without having webpack shim global = window.
Note: updated Gruntfile.js to have jshint read the config file from the
closes directory/parent directory and added a new .jshintrc to /shim to
lint the files there with a browser environment in mind.
=> update shim files to use window instead of global

package.json, src/core/Ros.js, src/core/SocketAdapter.js, src/core/Topic.js, src/util/cborTypedArrayTags.js, test/cbor.test.js, test/karma.conf.js, test/require-shim.js
Goes with https://github.com/RobotWebTools/rosbridge_suite/pull/364
=> Add support for CBOR encoding

src/core/Topic.js
Fix forward compatibility issues by not requesting compression from the server that we can't actually decompress.
=> Don't allow unsupported compression types

src/util/cborTypedArrayTags.js, test/cbor.test.js
Typed array decoding was broken when the typed array was not the last item in the encoded message.  Added a failing test then fixed it.
=> Fix CBOR native array decoding offset

src/tf/TFClient.js
I'm using the ES6 import statement to load roslib which works fine for
most roslib modules, except `TFClient`. That module doesn't properly
import it's dependencies but relies on the properties on the ros object.
I rewrote it a little bit to make it work for ES6 imports. Should be
backwards compatible.
=> Fix TypeError: this.ros.ActionClient is not a function

src/urdf/UrdfModel.js
Some robot's definition has empty string for material's name. And the empty string caused `this.materials` mess up. 
This fix the problem.
=> Support the case material's name is empty string

.github/workflows/main.yml
Branches need to be up-to-date when merging to `develop`, so `pull_request` and `push` runs are the same.
https://github.com/RobotWebTools/roslibjs/pull/426 Shows that PRs to other branches than `develop` do run the `pull_request`.
The `pull_request` runs on this PR are actually from https://github.com/RobotWebTools/roslibjs/pull/426.
=> (actions) dont't run pull_request on develop

.github/workflows/main.yml, test/build.bash
Instead of requiring the build to be up-to-date, GH actions will push the build folder when the CI procedure has resulted in a diff.
To test it, I added some commits to push on this feature branch. The commit done by GH actions: https://github.com/RobotWebTools/roslibjs/pull/446/commits/5112758bd684e31c5bdefaf562e52ce0cd1d7575
GH actions run: https://github.com/RobotWebTools/roslibjs/runs/2758087742?check_suite_focus=true
I dropped these commits again and forced pushed. I can't guarantee this will work with the branch protection on `develop`. But merge this PR is the only way to find out. There is no other way to test this.
Once approved, I will apply this to ros3djs and ros3djs too.
=> Auto Build

.github/workflows/main.yml
**Public Changes**
None
**Description**
Also run GH actions on PRs. As action runs on a PR from a fork don't show up correctly.
=> (actions) also run on PR.

src/tf/TFClient.js, test/tfclient.test.js
**Public API Changes**
None
**Description**
If a TFClient is disposed while a service call to update the goal is ongoing it will subscribe to the republished topic even if already disposed. To prevent this we mark the TFClient as disposed when it is disposed, and check for this in the service callback.
Fixes #488
=> Prevent race condition in TFClient

package-lock.json, package.json, src/util/workerSocket.js
=> Use webworkify-webpack with webpack

src/actionlib/ActionClient.js
**Public API Changes**
This PR makes the following channel omission flags for `ActionClient` explicitly visible to the user via JSDoc's `@param` tag:
- `omitFeedback`
- `omitStatus`
- `omitResult`
**Description**
This change is in line with PR #202. This PR explicitly allows the aforementioned channel omission flags to be passed in as part of the `options` parameter of the constructor function of `ActionClient`.
=> Add channel omission flags to ActionClient's JSDoc param tag

README.md
Demos are not hosted anymore
Fixes: https://github.com/RobotWebTools/roslibjs/issues/584
=> (README) remove link to demos

examples/fibonacci.html, examples/fibonacci_server.html, examples/math.html, examples/simple.html, examples/tf.html, examples/urdf.html
As this is included in the build
Fixes https://github.com/RobotWebTools/roslibjs/issues/614
=> (examples) no need for EventEmitter CDN

src/core/Ros.js
**Public API Changes**
None
**Description**
Before this change, `typeDefDict[fieldName]` was always assigned as an array, irrespective of other variables’ states. With this new update, if the `arrayLen` is equal to `-1`, the `typeDefDict[fieldName]` is assigned the non-array value `fieldType`. If `arrayLen` doesn't equal `-1`, the assignment remains an array format, `[fieldType]`.
We used this to successfully [decode ROS2 nested types](https://github.com/RobotWebTools/rosbridge_suite/pull/883).
#463
=> Ensure `fieldType` is a scalar if `arrayLen` is `-1`
